language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
env:
  - STRATIC_TEST_EXPENSIVE=true
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-stratic' ]; then cd .. && eval "mv $currentfolder generator-stratic" && cd generator-stratic; fi
after_script: ./node_modules/.bin/coveralls < coverage/lcov.info
